### ISSUE TITLE
wollfaden fixiert einen punkt dort, wo die wolle den screen wechselt

### ISSUE THREAD

**Issue by kleeder** [kleeder/BattleBitGameJam#12]
kann man es irgendwie abändern, dass der faden beim screenwechsel generell den ersten soliden block unter dem punkt wo die wolle den screen wechselt, als fixpunkt nimmt?

**Comment by kleeder** [comment]
gar nicht wahr, es fixiert irgendwie immer an diesem punkt, egal wo sie wechselt 
![image](https://user-images.githubusercontent.com/32968597/45917090-94640e80-be70-11e8-8b4c-a4d62755019f.png)

**Comment by Nimo139** [comment]
ja ist mir auch aufgefallen, ich weiß noch nicht ob die wolle da die an der decke festhängt oder ob das immer ist

**Comment by kleeder** [comment]
könnte man testen, indem man die blöcke dort entfernt und abändert

**Comment by kleeder** [comment]
sie scheint da an der decke festzuhängen, wie eingehende tests bewiesen haben.
ich close dieses issue jetzt mal, da wir einfach drumherum bauen könnten, so dass es im fertigen leveldesign nicht auftritt :D/
