### ISSUE TITLE
noch ausstehende sprites (& Verbesserungen)

### ISSUE THREAD

**Issue by Nimo139** [kleeder/BattleBitGameJam#19]
Katzen durchlässig #248
Woll    durchlässig #247

**Comment by kleeder** [comment]
ausstehende sprites:
Katzen durchlässig #248
Woll durchlässig #247
- final level boden & deko
- höhlenlevel deko(?)
- 3 große bilder für menü

**Comment by kleeder** [comment]
ausstehende sprites:
- final level
