### ISSUE TITLE
Bodenlose Wolle

### ISSUE THREAD

**Issue by Nimo139** [kleeder/BattleBitGameJam#20]
Wole durchhängen lassen bei den Lavalöchern

**Comment by kleeder** [comment]
nicht nur lavalöcher sondern generell abgründe usw

**Comment by Nimo139** [comment]
![grafik](https://user-images.githubusercontent.com/12942779/46509112-2ab90c80-c841-11e8-98ee-54f4613cc842.png)

**Comment by Nimo139** [comment]
Am Boden ist es behoben, weiter oben... naja :D
