### ISSUE TITLE
wasser (2 sprites) mit 2-bild-animation

### ISSUE THREAD

**Issue by kleeder** [kleeder/BattleBitGameJam#21]

**Comment by Nimo139** [comment]
![lava](https://user-images.githubusercontent.com/12942779/46320057-d31a6700-c5dc-11e8-84a1-5fc33df07a68.gif)

**Comment by Nimo139** [comment]
Animationsfunktion ist vorhanden, momentan nur mit mit 2 sprites, weiter Animationsblöcke können sehr einfach hinzugefügt werden. Falls mehr frames pro Block sollen, muss es angepasst werden. Alles läuft auf der selben frequenz...
