### ISSUE TITLE
wolle verbrennt in lava, schwimmt aber im wasser

### ISSUE THREAD

**Issue by kleeder** [kleeder/BattleBitGameJam#23]

**Comment by Nimo139** [comment]
wie soll sie schwimmen? also kein solider block sonder so halb an der oberfläche? und dann? kann die katze ins wasser?

**Comment by Nimo139** [comment]
Verbrennen in Lava ist == Kaktus, okay?

**Comment by kleeder** [comment]
verbrennen == kaktus geht klar!

ich war mir beim schwimmen auch unsicher.. am besten frage ich nochmal ali, ob er da ne idee hat

**Comment by kleeder** [comment]
wasser ist nicht notwendig, wir bleiben bei lava
