### ISSUE TITLE
wolle verbindungsprobleme

### ISSUE THREAD

**Issue by Nimo139** [kleeder/BattleBitGameJam#24]
![grafik](https://user-images.githubusercontent.com/12942779/46317802-9185be00-c5d4-11e8-9675-6be9f3245f2a.png)

**Comment by Nimo139** [comment]
![grafik](https://user-images.githubusercontent.com/12942779/46572117-e92f7b00-c980-11e8-8fef-93bcdf19efc7.png)

**Comment by Nimo139** [comment]
![grafik](https://user-images.githubusercontent.com/12942779/46572319-13cf0300-c984-11e8-9e1f-b75bdd8f7bf3.png)

**Comment by kleeder** [comment]
wont fix
