### ISSUE TITLE
nadel ist leicht versetzt, wenn man den wollblock "falsch" daraufkickt

### ISSUE THREAD

**Issue by kleeder** [kleeder/BattleBitGameJam#6]
probiert es aus, kickt die wolle auf die nadel, manchmal trifft die wolle leicht hinter der nadel auf und der sprite der nadel verschiebt sich.
unschön >.<

**Comment by Nimo139** [comment]
an jedem der 8 pixel in einem Block konnte die nadel gesetzt werden. jetzt wird abgerundet, passt
