### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Nimo139** [kleeder/BattleBitGameJam#9]
in fg ist viel platz da könnte ein großes Katzu logo hin 64x40 oder so, also wirklich groß :D

**Comment by kleeder** [comment]
in FG sind nun 3 sprite-bereiche, die genutzt werden können für 3 kleine bildchen, welche auf dem menüscreen gerendert werden (und/oder auf dem game-won-screen)

**Comment by kleeder** [comment]
Duplicate of #19
